name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The PR title is ${{ github.event.pull_request.title }}."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: [[ ${{ github.event.pull_request.title }} =~ ^(chore|feat|fix)\\(CP4SCORE-[0-9]{5,}\\): ]] && exit 0 || exit 1
      - run: echo "🍏 This job's status is ${{ job.status }}."
